In [13]:
import pandas as pd

In [14]:
players_csv = "Clean/players_clean.csv"
games_details_csv = "Clean/games_details_clean.csv"

In [15]:
players_df = pd.read_csv(players_csv)
games_details_df = pd.read_csv(games_details_csv)

In [16]:
players_df.head()

   Unnamed: 0            Player  Player ID     Team ID
0           0     Royce O'Neale    1626220  1610612762
1           1  Bojan Bogdanovic     202711  1610612762
2           2       Rudy Gobert     203497  1610612762
3           3  Donovan Mitchell    1628378  1610612762
4           4       Mike Conley     201144  1610612762

In [17]:
games_details_df.head()

,Unnamed: 0,Team ID,Team Abbr,City,Player ID,Position,Minutes,Field Goals Made,Field Goals Attempted,Field Goals %,3 Pt Field Goals Made,3 Pt Field Goals Attempted,3 Pt Field Goals %,Free Throws Made,Free Throws Attempted,Free Throws %,Rebounds,Assists,Personal Fouls,Points
0,0,1610612764,WAS,Washington,203078,F,34:36:00,14.0,28.0,0.500,1.0,6.0,0.167,4.0,6.0,0.667,4.0,3.0,0.0,33.0
1,1,1610612764,WAS,Washington,1629060,F,25:50:00,4.0,6.0,0.667,1.0,1.0,1.000,2.0,3.0,0.667,7.0,1.0,4.0,11.0
2,2,1610612764,WAS,Washington,203458,C,12:11,3.0,5.0,0.600,0.0,0.0,0.000,0.0,0.0,0.000,5.0,0.0,2.0,6.0
3,3,1610612764,WAS,Washington,203526,G,19:19,2.0,5.0,0.400,0.0,2.0,0.000,0.0,0.0,0.000,3.0,1.0,2.0,4.0
4,4,1610612764,WAS,Washington,201566,G,29:07:00,2.0,10.0,0.200,0.0,3.0,0.000,6.0,10.0,0.600,6.0,11.0,0.0,10.0

In [18]:
details_df = pd.merge(players_df, games_details_df, on="Player ID")
details_df.head()

,Unnamed: 0_x,Player,Player ID,Team ID_x,Unnamed: 0_y,Team ID_y,Team Abbr,City,Position,Minutes,...,3 Pt Field Goals Made,3 Pt Field Goals Attempted,3 Pt Field Goals %,Free Throws Made,Free Throws Attempted,Free Throws %,Rebounds,Assists,Personal Fouls,Points
0,0,Royce O'Neale,1626220,1610612762,75,1610612762,UTA,Utah,F,33:53:00,...,4.0,6.0,0.667,0.0,0.0,0.0,8.0,3.0,4.0,14.0
1,0,Royce O'Neale,1626220,1610612762,343,1610612762,UTA,Utah,F,36:32:00,...,1.0,3.0,0.333,0.0,0.0,0.0,5.0,3.0,3.0,3.0
2,0,Royce O'Neale,1626220,1610612762,1020,1610612762,UTA,Utah,F,28:03:00,...,2.0,6.0,0.333,1.0,2.0,0.5,2.0,2.0,2.0,9.0
3,0,Royce O'Neale,1626220,1610612762,1287,1610612762,UTA,Utah,F,28:40:00,...,2.0,3.0,0.667,0.0,0.0,0.0,7.0,2.0,3.0,6.0
4,0,Royce O'Neale,1626220,1610612762,1782,1610612762,UTA,Utah,G,30:34:00,...,0.0,3.0,0.000,0.0,0.0,0.0,8.0,3.0,3.0,2.0

In [21]:
min_details_df = details_df[["Player", "Player ID", "Team ID_x", "Team ID_y", "Team Abbr", "City", "Position", "Minutes",
                            "Field Goals Made", "Field Goals Attempted", "Field Goals %", "3 Pt Field Goals Made",
                            "3 Pt Field Goals Attempted", "3 Pt Field Goals %", "Free Throws Made", "Free Throws Attempted",
                            "Free Throws %", "Rebounds", "Assists", "Personal Fouls", "Points"]]
min_details_df.head()

,Player,Player ID,Team ID_x,Team ID_y,Team Abbr,City,Position,Minutes,Field Goals Made,Field Goals Attempted,...,3 Pt Field Goals Made,3 Pt Field Goals Attempted,3 Pt Field Goals %,Free Throws Made,Free Throws Attempted,Free Throws %,Rebounds,Assists,Personal Fouls,Points
0,Royce O'Neale,1626220,1610612762,1610612762,UTA,Utah,F,33:53:00,5.0,7.0,...,4.0,6.0,0.667,0.0,0.0,0.0,8.0,3.0,4.0,14.0
1,Royce O'Neale,1626220,1610612762,1610612762,UTA,Utah,F,36:32:00,1.0,6.0,...,1.0,3.0,0.333,0.0,0.0,0.0,5.0,3.0,3.0,3.0
2,Royce O'Neale,1626220,1610612762,1610612762,UTA,Utah,F,28:03:00,3.0,7.0,...,2.0,6.0,0.333,1.0,2.0,0.5,2.0,2.0,2.0,9.0
3,Royce O'Neale,1626220,1610612762,1610612762,UTA,Utah,F,28:40:00,2.0,3.0,...,2.0,3.0,0.667,0.0,0.0,0.0,7.0,2.0,3.0,6.0
4,Royce O'Neale,1626220,1610612762,1610612762,UTA,Utah,G,30:34:00,1.0,8.0,...,0.0,3.0,0.000,0.0,0.0,0.0,8.0,3.0,3.0,2.0