In [7]:
import pandas as pd

In [8]:
ranking_csv = "Clean/ranking_clean.csv"
games_details_csv = "Clean/games_details_clean.csv"

In [9]:
ranking_df = pd.read_csv(ranking_csv)
games_details_df = pd.read_csv(games_details_csv)

In [4]:
games_details.head()

,Unnamed: 0,Team ID,Team Abbr,City,Player ID,Position,Minutes,Field Goals Made,Field Goals Attempted,Field Goals %,3 Pt Field Goals Made,3 Pt Field Goals Attempted,3 Pt Field Goals %,Free Throws Made,Free Throws Attempted,Free Throws %,Rebounds,Assists,Personal Fouls,Points
0,0,1610612764,WAS,Washington,203078,F,34:36:00,14.0,28.0,0.500,1.0,6.0,0.167,4.0,6.0,0.667,4.0,3.0,0.0,33.0
1,1,1610612764,WAS,Washington,1629060,F,25:50:00,4.0,6.0,0.667,1.0,1.0,1.000,2.0,3.0,0.667,7.0,1.0,4.0,11.0
2,2,1610612764,WAS,Washington,203458,C,12:11,3.0,5.0,0.600,0.0,0.0,0.000,0.0,0.0,0.000,5.0,0.0,2.0,6.0
3,3,1610612764,WAS,Washington,203526,G,19:19,2.0,5.0,0.400,0.0,2.0,0.000,0.0,0.0,0.000,3.0,1.0,2.0,4.0
4,4,1610612764,WAS,Washington,201566,G,29:07:00,2.0,10.0,0.200,0.0,3.0,0.000,6.0,10.0,0.600,6.0,11.0,0.0,10.0

In [10]:
ranking.head()

,Unnamed: 0,Team ID,Conference,Team,Games,Wins,Losses,Wins %,Record Home,Record Away
0,0,1610612762,West,Utah,72,52,20,0.722,31-5,21-15
1,1,1610612756,West,Phoenix,72,51,21,0.708,27-9,24-12
2,2,1610612743,West,Denver,72,47,25,0.653,25-11,22-14
3,3,1610612746,West,LA Clippers,72,47,25,0.653,26-10,21-15
4,4,1610612742,West,Dallas,72,42,30,0.583,21-15,21-15

In [12]:
ranking.groupby('Team').Wins.sum().sort_values(ascending=False).plot.bar(figsize=(15,6))
plt.title = ("Winnings")
plt.xlabel("NBA Teams")
plt.ylabel("Points")
plt.show()

MemoryError: Unable to allocate 29.5 GiB for an array with shape (3963079127,) and data type int64

In [ ]:
details_df = pd.merge(ranking_df, games_details_df, on="Team ID")
details_df.head()